const numero = Number(prompt('Digite seu número'));
const numeroTitulo = document.getElementById('numero-titulo');
const texto = document.getElementById('texto');
numeroTitulo.innerHTML = numero;
texto.innerHTML += `<p>Seu número +2 é: ${numero + 2}</p>`;
texto.innerHTML += `<p>Arredondado pra cima é: ${Math.ceil(numero)}</p>`;
texto.innerHTML += `<p>arredondado pra baixo é: ${Math.floor(numero)}</p>`;
texto.innerHTML += `<p>A raiz quadrada é: ${numero ** 0.5}</p>`
texto.innerHTML += `<p>${numero} É número inteiro: ${Number.isInteger(numero)}</p>`
texto.innerHTML += `<p>Com duas casas decimais: ${numero.toFixed(2)}</p>`
texto.innerHTML += `<p> é NaN?: ${Number.NaN(numero)}</p>`